- .gitignore
- .pylintrc
- .travis.yml
- README.rst
- adafruit_bno055.py
- readthedocs.yml
I haven't tested these changes on device yet. Please only merge you test it or I follow up later to say its tested.
For https://github.com/adafruit/circuitpython/issues/475
> Update to new build process and turn on lint.

- adafruit_bno055.py
> Fix gyro scaling for degrees. Temperature is signed byte.

- adafruit_bno055.py
This fixes two issues with the mode setter.
Firstly, as per issue #26, it is necessary to set `_CONFIG_MODE` prior to making any other mode change. The datasheet is misleading on this but it is empirically necessary.
Secondly the datasheet mandates delays after setting and clearing `_CONFIG_MODE`.
Please note that I have no means of running CircuitPython: I have tested this code against MicroPython only.
> mode setter enables changes and honors delays.

- adafruit_bno055.py
- examples/bno055_simpletest.py
For #34.
- Had to bury the math in the scale parameter. Couldn't just math on the `_ScaledReadOnlyStruct` class. Decided not to import `math` just for `pi`.
- Marked `gyroscope` as deprecated
- Updated `bno055_simpletest.py` example
- webgl example is OK as is, doesn't seem to use gyro
- Tested with Itsy M4 and updated `bno055_simpletest.py`
> Change to gyro and rads/sec

- adafruit_bno055.py
issue #21 
builds on work by @katlings and replaces [her PR](https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/22)
implements the approach suggested by @deshipu and addresses feedback from @caternuson
note - assignment is fighting against BNO055 auto-calibration so can have odd behavior
```
Adafruit CircuitPython 4.0.0-rc.1 on 2019-04-23; Adafruit Feather M4 Express with samd51j19
>>> import board, busio
>>> import adafruit_bno055 as bno055
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> bno = bno055.BNO055(i2c)
>>> bno.radius_magnetometer
0
>>> bno.radius_magnetometer = 40
>>> bno.radius_magnetometer = 40
>>> bno.radius_magnetometer
1
>>> bno.radius_magnetometer
0
>>> bno.offsets_accelerometer = 1, -1, 1
>>> bno.offsets_accelerometer
(1, -1, 1)
```
> Add calibration offsets and radii as properties on BNO055 library

- adafruit_bno055.py
- examples/bno055_simpletest.py
- examples/bno055_webgl_demo/server.py
For #41 
**BREAKING CHANGE**
- Adds UART support
- Classes refactored into base and I2C/UART specific subs
- examples updated
Tested on Itsy M4.
```python
Adafruit CircuitPython 5.1.0 on 2020-04-02; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> import adafruit_bno055
>>> bno = adafruit_bno055.BNO055_UART(board.UART())
>>> bno.acceleration
(0.12, -0.43, 9.99)
>>> bno.acceleration
(0.06, -8.53, 5.27)
>>> bno.acceleration
(-3.65, 8.36, 1.48)
>>> bno.acceleration
(-8.49, -4.86, -1.55)
>>> 
```
> Add UART support

- adafruit_bno055.py
Changing _gyro property from incorrect magnetic register address from MAG_DATA_X_LSB 0x0E to gyro address  GYR_DATA_X_LSB 0x14
> Register reference fix for GYR_DATA_X_LSB

- adafruit_bno055.py
- docs/conf.py
- examples/bno055_simpletest.py
So I tried a bunch of different ways involving checking how many bytes were in waiting, but in the end, just making the time.sleep smaller and adding a try/except loop was the fastest and most stable way to do it.
> Allow uart to go ~100Hz versus 10Hz

- adafruit_bno055.py
I can do this with the other sensors as well if you'd like me to.
> Added ability to configure accelerometer

- README.rst
Using the `BNO055` class as written in the README results in a NotImplementedError. For the I2C example, the class `BNO055_I2C` needs to be used.
> Update README to use correct BNO055 class for I2C

- adafruit_bno055.py
Fixes #59 
Tested on a Feather M4 running CircuitPython 5.3.0
> Fixed super call to make pylint happy

- adafruit_bno055.py
Fixes issue #75 that I opened. When doing so, I found that the outputs mismatched what they should be for some additional modes as well, so I fixed them too: 
- Old code returned magnetometer values when in ACCONLY_Mode, fixed to add to excluded list
- Old code only returned Euler angles, quaternions, linear acceleration, and gravity values when in absolute orientation fusion modes. They are also valid and should be returned for relative orientation fusion modes (IMUPLUS and M4G). Fixed.
- The modes to output table in the comments was incomplete, as it did not list the relative orientation fusion modes. I added that column, clarified the language, and added a reference to the table in the datasheet to help maintainers and users.
> Fix fusion modes

- adafruit_bno055.py
This pull request will fix the issue https://github.com/adafruit/Adafruit_CircuitPython_BNO055/issues/79.
Only translate the lower 4 bits of the register OPR_MODE to the operation mode of the sensor.
> Fixed the operation mode reading issue

- README.rst
- adafruit_bno055.py
- docs/examples.rst
- docs/index.rst
- examples/bno055_simpletest.py
> improving_docs

- examples/bno055_webgl_demo/server.py
notifyAll was replaced with notify_all. notifyAll still just goes to notify_all but it's deprecated so it made pylint mad
https://docs.python.org/3/library/threading.html
> Fixed deprecated method

- adafruit_bno055.py
Resolves #95 by exposing the existing setting for Suspend power mode, as well as matching method for Normal mode.  Though the request says "low power mode" that actually is something different than the function method in it.  I could also expose that as well, but it may take more effort to explain how Lower Power mode affects reading sensors than Suspend mode, so maybe another issue/PR :)
> Expose Suspend power mode

- adafruit_bno055.py
resolves #85 
submitted for review / comment
> Add missing type annotations

- examples/bno055_calibrator.py
`bno055_calibrator.py` is a CircuitPython module for calibrating the BNo055 9-DoF sensor. After the sensor is manually
calibrated, the module produces calibration preset offset tuples for use in project code.
> add a calibration method to the examples folder

- adafruit_bno055.py
@ladyada 
Resolves: #124 
I found the mentioned portion of the datasheet that says these can be updated in CONFIGMODE
> ensure config mode before setting range or bandwidth settings

- examples/bno055_compass_mode.py
@ladyada 
Resolves: #100 
Added the formula and code shared in that issue to the repo and did a quick test with picow and BNO055. I found that `magnetic` property is passing through the value from `_magnetic` so I had the example use the public one instead.
> compass mode example
